local Info = {
    ["All Clans"] = {
        ["Shinigami"] = {
            "Sozosei",
            "Shihouin",
            "Urahara",
            "Yamamoto",
            "Hyosube",
            "Zaraki",
            "Shutara",
            "Tsunayashiro"
        },
        ["Hollow"] = {
            "Ikomikidomoe",
            "Starrk",
            "Odelschwanck",
            "Louisenbairn",
            "Jaegerjaquez",
            "Cifer",
        },
        ["Quincy"] = {
            "Ishida",
            "Kurosaki",
            "Du",
            "Valkyire",
            "B",
            "Parnkgjas",
            "Le vaar"
        },
        ["Fullbringer"] = {
            "Ubuginu",
            "Orihime",
            "Sado",
            "Ginjo",
            "Tsukishima"
        },
    },
    ["AllCodes"] = {
        "codelolhaha",
        "codeofdoom",
        "600MVisits",
        "300KLikes",
        "serverlistfixed",
        "thosewhoknowemblem";
        "superduperfunsecretcode",
        "wowshutdowncodeyeah",
        "codeforshutdownisuppose",
        "yesterdayshutdown",
        "thanksfor900k",
        "setrona1vertagzeu0",
        "excaliburfool",
        "higuyscode",
        "thisiswhywetestthosewhoknow",
        "goplayranked",
        "somebugsfixes",
        "800kcodeyeah",
        "thanksforpatience",
        "raidsfixed",
        "compensationforinconvenientrelease",
        "sorryforthebankbugs",
        "mythoughtsonthislater",
        "3daysthosewhoknow",
        "rerererelease",
        "privateservercompensation",
        "promiseddecembercode"
    },
    ["All Elements"] = {
        ["Hollow"] = {
            "Bone",
            "Slash",
            "Storm",
            "Acid",
            "Shark",
            "Phoenix",
            "Pantera",
            "Spirit",
            "Devil",
            "Starrk",
            "Vampire",
            "Volcanica",
            "Arrogante",
            "Horse",
            "Light",
            "Snake"
        },
        ["Shinigami"] = {
            "Weight",
            "Wind",
            "Poison",
            "Shadow",
            "Creation",
            "Lightning",
            "Ash",
            "Confusion",
            "Shinso",
            "Water",
            "Berserk",
            "Judgement",
            "Zangetsu",
            "Fire",
            "Assimilation",
            "Suzumebachi",
            "Theatre",
            "Flower",
            "Ice",
            "Blood",
            "Ink",
            "Snow",
            "Kyoka Suigetsu",
            "Duality",
            "Benihime"
        },
        ["Quincy"] = {
            "Heat",
            "Wind",
            "Iron",
            "Overkill",
            "Thunderbolt",
            "Fear",
            "Power",
            "Compulsory",
            "Nimble",
            "Miracle",
            "Visionary",
            "Glutton",
            "Superstar",
            "Explode",
            "Butterfly",
            "X-Axis",
            "Royal",
            "Zombie",
            "Balance",
            "Deathdealing"
        },
        ["Fullbringer"] = {
            "Devils Arm",
            "Dollhouse",
            "Time Tells No Lies",
            "Zangetsu",
            "Chess",
            "Book of the End"
        }
    },
    ["All Weapons"] = {
        ["Shinigami"] = {
            "Hammer",
            "Twinblade",
            "Spear",
            "Katana",
            "Greatsword",
            "Dual Swords",
            "Scythe",
            "Longsword", 
            "Dagger",
            "Rapier",
            "Odachi"
        },
        ["Hollow"] = {
            "Tessen",
            "Ulquiorra's Katana",
            "Nelliel's Lance",
            "Baraggan's Axe",
            "Wonderweiss's Sword",
            "Nnoitra's Scythe",
            "Harribel's Dagger",
            "Nelliel's Katana",
            "Elipson",
            "Verglas",
            "Cloudsplitter",
            "Destello",
            "Scar",
            "Serpentinitebreaker",
            "Hollowburden",
            "Calibre",
            "Bloodedge",
            "Heatpiercer",
            "Piety",
        },
        ["Quincy"] = {
            "Antithesis",
            "Quincy Cutlass",
            "Quilge's Saber",
            "Jugram's Freund Schild",
            "Jugram's Broadsword",
            "Schwert",
            "Shadesworn",
            "Quincy Glock",
            "Spalten",
            "Reichweite",
            "Kehren",
            "Great Lance"
        },
        ["Fullbringer"] = {
        },
    }
}

return Info
